### ISSUE TITLE
Convert Project Structure from PyScaffold to Poetry

### ISSUE THREAD

**Issue by matthewm8m** [matthewm8m/Terrain-Generator#2]
Currently, the project uses PyScaffold to run. Instead, we should use Poetry because it has a lower profile and is more efficient than Pipenv. This requires the following actions to be taken:

- [ ] Move all of the source files to a new directory.
- [ ] Initialize a Poetry project with the same dependencies.
- [ ] Update documentation including the `README` and `LICENSE`.
